skip_tags: true

environment:
    github_access_token:
        secure: tK9azIJKQNkcoFHSVVGi1/89y67K8vR3iqX2w8EYjqf7peLj4cLPTcL3ypeUI18G

init:
    - git config --global core.autocrlf true

install:
    - cmd: .paket\paket.bootstrapper.exe

before_build:
    - cmd: .paket\paket.exe install

build_script:
    - cmd: packages\build\GitVersion.CommandLine\tools\GitVersion.exe /l console /updateassemblyinfo /exec "packages\build\FAKE\tools\FAKE.exe" /execArgs "scripts\build.fsx"

test: off

artifacts:
  - path: artifacts\**\*.*

deploy:
  - provider: NuGet
    api_key:
        secure: W4LIy99ZYgP5/Ui81T8auRWPn0SNTPUH77+z7l/YFQ7e+OS48IxeX7zOiu913Req
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
        branch: master

on_success:
    - ps: |
        if ($env:GitVersion_BranchName -eq "master")
        {
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
            git tag $env:GitVersion_FullSemVer
            git push origin $env:GitVersion_FullSemVer -q
        }
        else
        {
            Write-Host "Don't tag current commit because we're on branch `"$env:GitVersion_BranchName`"."
        }

notifications:
    - provider: Email
      to:
        - j.egger@posteo.at
      on_build_status_changed: true
